# Generated by Django 5.1 on 2024-08-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProvider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('totalFund', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isApproved', models.BooleanField(default=False)),
                ('approvalDate', models.DateField(blank=True, null=True)),
                ('deadLine', models.DateField()),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payDay', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('minimumPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximumPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isApproved', models.BooleanField(default=False)),
                ('items', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.employee')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanprovider')),
            ],
        ),
    ]
