# Generated by Django 5.1 on 2024-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanprovider',
            name='provider_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
