# Generated by Django 5.1 on 2024-09-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_customer_customer_name_employee_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='request_id',
            new_name='loan_id',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approvalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='deadLine',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='interestRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='maximumPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='minimumPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='payDay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
